# This file was generated by GoReleaser. DO NOT EDIT.
cask "memento" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "ca3a058f3787de7f408dbffef0ececfb7b606a59145e320cd879342822bab911"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f000786358fa9796939d3c1e5f5e948f8bd9cb288685f83b3d56b38068dd395"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec4bb9b82c11ef2e8ec2523581dbb76b160ee425b9a30462fce5f67f312785d9"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "533cab3866f42f5bfbf1c90326cd765d655fa76e2ff3c7d34f8290b34f4c0aec"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_linux_arm64.tar.gz"
    end
  end

  name "memento"
  desc "Local-first, git-tracked knowledge wiki for codebases"
  homepage "https://github.com/hgilani/memento"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memento"

  # No zap stanza required

end
