# This file was generated by GoReleaser. DO NOT EDIT.
cask "memento" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "d8985cf3c46a58c4ceb1f84dac26784f44573503f0632c2f03dbc3919d8fe3c2"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "23ce1679447b4ffcead9c9f9ea701c596baf2618e14f3cdd779fcffc623a4515"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b0075f297f56aa4196862cc9722740fcfb5163e61afce8ac14807ddd673d087"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfdb31802bcbf9b5f9574c17fd7a67e9938922e277df69fbbc8e796fd644d40a"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_linux_arm64.tar.gz"
    end
  end

  name "memento"
  desc "Local-first, git-tracked knowledge wiki for codebases"
  homepage "https://github.com/hgilani/memento"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memento"

  # No zap stanza required

end
