# This file was generated by GoReleaser. DO NOT EDIT.
cask "memento" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "aa2a44b9dac3221855a9d4cb2405e39e9ee045c28f41b3c8e928f91e99260097"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9362b470d43a14703692819ce62cf264f163874efdcade83873288b53f609d26"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eaf171ec7b1390e58b01b99083ef4748d7110b1445175122dcae76f7dd46ec6b"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb438b71f4c462ca74afcbe152513dd46ff6ec20df3708258a966f1036af4d6b"
      url "https://github.com/hgilani/memento/releases/download/v#{version}/memento_#{version}_linux_arm64.tar.gz"
    end
  end

  name "memento"
  desc "Local-first, git-tracked knowledge wiki for codebases"
  homepage "https://github.com/hgilani/memento"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memento"

  # No zap stanza required

end
